project:
  type: website

execute:
  freeze: auto

website:
  # title: "TUHH Institute of Entrepreneurship"
  site-url: https://tuhhstartupengineers.github.io
  # repo-url: https://github.com/j0nasw/j0nasw.github.io
  page-navigation: true
  reader-mode: false
  search: true
  favicon: ./assets/favicon.ico

  cookie-consent:
    type: express
    style: headline
    palette: dark

  twitter-card: true

  open-graph:
    locale: de_DE
    site-name: Jonas Wilinski

  navbar:
    pinned: true
    logo: "assets/logo/logo_tie_white.svg"
    logo-alt: "TIE Logo"
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: transfer.qmd
        text: Transfer
      - href: about.qmd
        text: About
    right:
      # - icon: github
      #   href: "{{<var author.github>}}"
      #   aria-label: Quarto GitHub
      - icon: envelope
        href: mailto:tie@tuhh.de
        aria-label: Drop us a Mail
      # Icons can be found at https://icons.getbootstrap.com/

  sidebar:
    style: "floating"
    search: true
    contents: auto

  page-footer:
    left:
      © {{< var website.c_year >}} by [{{< var author.name >}}]({{< var author.url >}})<br>
      [Imprint](imprint.qmd) | [Data Privacy](privacy.qmd)
    right:
      Made with {{< var tech.quarto >}}<br>
      View the source at [GitHub]({{< var website.github >}})
    border: false
    background: dark

format:
  html:
    theme:
      light:
        - "themes/tie_dark.scss"
      dark: "themes/tie_dark.scss"
    toc: true
    toc-depth: 2
    toc-title: Contents
    author: "TIE"
    page-layout: full
